services:
  # PostgreSQL Database
  - type: postgresql
    name: customer-tracker-db
    plan: free

  # Web Service
  - type: web
    name: customer-tracker-web
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: customer-tracker-db
          property: connectionString
    healthCheckPath: /api/health
    autoDeploy: true
